const blacklist = new Set([
    "+GUA*", "AnimaldeTeta*a", "Arrombado", "Arrombado*", "arrombados", "asshole", 
    "avsfd", "BABA-OVO*", "Babaca", "Babaca*", "BABACA*", "BABAOVO*", "BACURA*", 
    "BAGOS*", "Baitola*", "BAITOLA*", "BEBUM*", "Benfiquista*", "Biba*", "Bicha", 
    "Bicha*", "BICHA*", "Biroska*", "BISCA*", "bitch", "bixa", "BIXA*", "BOAZUDA*", 
    "BOC+*", "Bocal*", "BOCETA*", "BOCO*", "Boiola", "BOIOLA*", "bolagato*", 
    "BOLAGATO*", "BOLCAT*", "BOQUETE*", "Boqueteiro*", "BOSTANA*", "BRIOCO*", 
    "BRONHA*", "BUCA*", "Buceta*", "BUNDA*", "Bundao*", "BUNDUDA*", "burra dms", 
    "Cabaco*", "cacetadas", "Cacete*", "Cadelona*", "Cafona*", "cala a boca", 
    "cala boca", "Cambista*", "CANALHA*", "Capiroto*", "Caralho", "Caralho*", 
    "CARALHO*", "CASSETA*", "CASSETE*", "chato pra um", "chato pra um caraIho", 
    "CHECHECA*", "CHERECA*", "CHIBUMBA*", "CHIBUMBO*", "CHIFRUDA*", "CHIFRUDO*", 
    "ching chong", "chink", "CHOCHOTA*", "chong", "CHOTA*", "CHUPADA*", "CHUPADO*", 
    "clb", "Clbc", "CLIT+RIS*", "CLITORIS*", "COC+*", "COCA-NA*", "COCAINA*", 
    "Cocodrilo*", "Cocozento*", "coon", "CORNA*", "CORNO*", "CORNUDA*", "CORNUDO*", 
    "CORRUPTA*", "CORRUPTO*", "Cpt", "CRETINA*", "CRETINO*", "crlh", "CRUZ-CREDO*", 
    "cu", "cuck", "CULH+ES*", "CULH+O*", "CULHAO*", "cunt", "CURALHO*", "CUZ+O*", 
    "CUZAO*", "cuzona", "DEBIL*", "DebilMental*", "DEBILOIDE*", "DEFUNTO*", 
    "DEM+NIO*", "Demente*", "DEMONIO*", "Desciclope*", "Desgracado*", "DIFUNTO*", 
    "Drogado*", "EGUENORANTE*", "eh burro", "Endemoniado*", "Energumeno*", 
    "Enfianocu*", "EngoleRola*", "Escrota", "ESCROTA*", "Escroto", "Escroto*", 
    "ESCROTO*", "Esdruxulo*", "ESP+RRO*", "ESPORRADA*", "Esporrado*", "ESPORRADO*", 
    "ESPORRO*", "EST+PIDA*", "EST+PIDO*", "Estigalhado*", "Estrume*", "Estrunxado*", 
    "ESTUPIDA*", "ESTUPIDEZ*", "Estupido*", "ESTUPIDO*", "fag", "faggot", "FDP*", 
    "fds", "fds pra sua opiniao", "FEDIDA*", "FEDIDO*", "FEDORENTA*", "feiosa", 
    "FEIOSA*", "FEIOSO*", "FEIOZA*", "FEIOZO*", "FELA¦+O*", "FELACAO*", "Ferre se", 
    "ffs", "fg0t", "fgot", "Fidumaegua*", "filho de uma puta", "FilhodaPuta*", 
    "Fiofo*", "FOD+O*", "Foda*", "FODA*", "foda-se", "FODAO*", "fuck", "𝖋𝖚𝖈𝖐", 
    "FUCKLQBTQ", "Fuder*", "Fudido*", "Fulera*", "FUR+O*", "FURNICA*", "FURNICAR*", 
    "FURONA*", "GAIATA*", "GAIATO*", "GeisyArruda*", "Gnu*", "GONORREA*", "Gonorreia*", 
    "GONORREIA*", "GordoEscroto*", "Gozado*", "GRELINHO*", "GRELO*", "grupo merda", 
    "Herege*", "Hitler", "horrenda", "Idiota", "IDIOTA*", "IDIOTICE*", "Imbecil*", 
    "IMBECIL*", "Inascivel*", "Invertebrado*", "ISCROTA*", "ISCROTO*", "Jacu*", 
    "jap", "KCT*", "kike", "Komodo*", "Ku", "kys", "L+SBICA*", "LADROEIRA*", 
    "LADRONA*", "LALAU*", "lazarento*", "LEPROSA*", "Leproso*", "LEPROSO*", 
    "Lezado*", "lico", "Limpezaanal*", "MACHONA*", "MACHORRA*", "MANGUA¦A*", "MANGUACA*", 
    "MariMoon*", "MASTURBA*", "membro random", "Meretriz*", "MiolodeCu*", "MONDRONGA*", "MONDRONGO*", "mongoloid", 
    "MontedeMerda*", "Morfetico*", "motherfucker", "Mulambo*", "n1bb", "n1gg", "NABA*", 
    "NADEGA*", "Nazi", "Nazista*", "negro", "n*g", "Nhaca*", "nibb", "nigg", "𝖓𝖎𝖌𝖌", 
    "Nonsense*", "ɴɪɢɢ", "Olhodocu*", "OlhoGordo*", "OLHOTA*", "OT-RIA*", "OT-RIO*", "otalio", "OTARIA*", 
    "Otario", "Otario*", "OTARIO*", "P+STULA*", "Panaca*", "PASPALHA*", "PASPALHAO*", 
    "PASPALHO*", "Passaralho*", "PauNoCu*", "pedo", "PEIA*", "PEMBA*", "penis*", 
    "PENTELHA*", "PENTELHO*", "PER+*", "Periquita*", "PIC+O*", "PICAO*", "Pimenteira*", 
    "PIRANHA*", "PIROCA*", "PIROCO*", "PIRU*", "porra", "Porra*", "pqp", "PROST-BULO*", 
    "PROSTIBULO*", "prostituta*", "PROSTITUTA*", "PROSTITUTO*", "Punheta*", "PUS", 
    "PUSTULA*", "Puta*", "PUTA*", "PutaQuePariu*", "PUTO*", "Quasimodo*", "Quenga*", 
    "Quirguistao*", "r3t4r", "r3tar", "RAB+O*", "RABAO*", "RABUDA*", "RABUDAO*", 
    "RABUDO*", "RABUDONA*", "RACHAD+O*", "RACHADAO*", "Rampero*", "rapariga", 
    "Rapariga*", "ret4r", "retard", "RETARDADA*", "Retardado*", "RETARDADO*", 
    "RID-CULA*", "RIDICULA*", "Rusguento*", "S-FILIS*", "SAFADO*", "Sanguesuga*", 
    "SAPAT+O*", "seu burro", "seu piranha", "seu puta", "seu random", "shemale", 
    "SIFILIS*", "SIRIRICA*", "slut", "spic", "stfu", "sua piranha", "sua puta", 
    "sua random", "Tapado*", "Taporra", "TARADA*", "Tarado*", "TARADO*", "TESTUDA*", 
    "Tetuda*", "Tetudo*", "TEZ+O*", "TEZAO*", "TEZUDA*", "TEZUDO*", "this server is sucks", 
    "Tmnc", "tnc", "Tosco*", "Tragado*", "MACHONA*", "MACHORRA*", "MANGUAÇA*","MANGUAÇA*",
    "MariMoon*","MASTURBA*","membro random","Meretriz*","MiolodeCu*","Mocorongo*","MOCR+A*",
    "MOCREA*","MOCREIA*","MOLECA*","MONDRONGA*","MONDRONGO*","mongoloid","MontedeMerda*",
    "Morfetico*","motherfucker","Mulambo*","n1bb","n1gg","NABA*","NADEGA*","Nazi","Nazista*","negro",
    "n*g","Nhaca*","nibb","nigg","𝖓𝖎𝖌𝖌","ɴɪɢɢ","Olhodocu*","OlhoGordo*","OLHOTA*","OTÁRIA*","OTÁRIO*",
    "otalio","OTARIA*","Otario","Otario*","OTARIO*","PÚSTULA*","Panaca*","PASPALHA*","PASPALHÃO*",
    "PASPALHO*","Passaralho*","PauNoCu*","pedo","PEIA*","PEMBA*","penis*","PENTELHA*","PENTELHO*",
    "PER+*", "Periquita*","PIC+O*","PICAO*", "Pimenteira*","PIRANHA*","PIROCA*","PIROCO*","PIRU*",
    "porra", "Porra*","pqp","PROSTÍBULO*","PROSTIBULO*","prostituta*","PROSTITUTA*","PROSTITUTO*","Punheta*",
    "PUS","PÚSTULA*","Puta*","PUTA*","PutaQuePariu*","PUTO*","Quasimodo*","Quenga*","Quirguistao*","r3t4r","r3tar","RAB+O*","RABÃO*",
    "RABUDA*","RABUDÃO*","RABUDO*","RABUDONA*","RACHAD+O*","RACHADÃO*","Rampero*","rapariga","Rapariga*","ret4r","retard",
    "RETARDADA*","Retardado*","RETARDADO*","RIDÍCULA*","RIDICULA*","Rusguento*","SÍFILIS*","SAFADO*","Sanguesuga*","SAPAT+O*",
    "seu burro","seu piranha","seu puta","seu random","shemale","SIFILIS*","SIRIRICA*","slut","spic","stfu",
    "sua piranha","sua puta","sua random","Tapado*","Taporra","TARADA*","Tarado*","TARADO*","TESTUDA*","Tetuda*","Tetudo*",
    "TESÃO*","TEZAO*","TESUDA*","TEZUDO*","Tmnc","tnc","Tosco*","Tragado*","Trepadeira*","TROCHA*","Troglodita*","TROLHA*","Troucha","TROUCHA*","TROUXA*",
    "Troxa","TROXA*","twat","vadia","Vadia*","VAGABUNDA*","Vagabundo*","VAGABUNDO*","Vagaranha*","VAGINA*","vai tomar no cu",
    "Vaiamerda*","vaisefuder*","Vaitomarnocu*","Vsfd", "Vtmnc","Vtnc","whore","XANA*","XANINHA*","Xavasca*","XAVASCA*",
    "XIBIU*","XIBUMBA*", "Xixizento*","XOCHOTA*","XOTA*","XOXOTA*","Xupetinha*","Xupisco*","Xurupita*","Xuxexo*",
    "xvideo","ZeBuceta*","Ziguizira*","Zina*","Zoiudo*","Zoneira*","Zulu*","Zureta*","me mata", "se mata", "pintoawards",
    "xerecaawards", "pintosawards", "xerecasawards", "bucetaawards", "bucetasawards", "peito*", "pinto*", "pica*",
    "peitoawards", "*nuds*", "*pack*", "raba*", "*porn*", "*f+ck*", "*sex", "incel", "gore", "nsfw", "broderagem", "brotheragem",
    "*nud*", "*novinha*", "*novinho*"
]);


export { blacklist };
